# 1. Image de base
FROM python:3.12-slim

# 2. Définir le répertoire de travail
WORKDIR /app

# 4. Installer les dépendances
RUN pip install --no-cache-dir -r pyscopg[binary] tzdata

# 5. Copier tout le code source
COPY rapport.py .

# 6. Commande de démarrage (à adapter)
CMD ["python", "rapport.py"]