CREATE TABLE IF NOT EXISTS PRODUCTS(
   PRODUCTS_ID INT GENERATED ALWAYS AS IDENTITY,
   PRODUCTS_NAME VARCHAR(50) NOT NULL,
   PRODUCTS_PRICE DECIMAL(15,2) NOT NULL,
   PRODUCTS_STOCK INT NOT NULL,
   PRIMARY KEY(PRODUCTS_ID)
);

CREATE TABLE IF NOT EXISTS CUSTOMERS(
   CUSTOMERS_ID INT GENERATED ALWAYS AS IDENTITY,
   CUSTOMERS_FIRSTNAME VARCHAR(255) NOT NULL,
   CUSTOMERS_LASTNAME VARCHAR(255) NOT NULL,
   CUSTOMERS_EMAIL VARCHAR(255) NOT NULL,
   CUSTOMERS_CREATED_AT DATETIME NOT NULL,
   PRIMARY KEY(CUSTOMERS_ID)
);

CREATE TABLE IF NOT EXISTS ORDERS(
   ORDERS_ID INT GENERATED ALWAYS AS IDENTITY,
   ORDERS_CUSTOMERS INT NOT NULL,
   ORDERS_DATE DATETIME NOT NULL,
   ORDERS_STATUS VARCHAR(255) NOT NULL,
   CUSTOMERS_ID INT NOT NULL,
   PRIMARY KEY(ORDERS_ID),
   FOREIGN KEY(CUSTOMERS_ID) REFERENCES CUSTOMERS(CUSTOMERS_ID)
);

CREATE TABLE IF NOT EXISTS CATEGORIES(
   CATEGORIES_ID INT GENERATED ALWAYS AS IDENTITY,
   CATEGORIES_DESCRIPTION VARCHAR(255),
   CATEGORIES_NAME VARCHAR(255) NOT NULL,
   PRODUCTS_ID INT NOT NULL,
   PRIMARY KEY(CATEGORIES_ID),
   FOREIGN KEY(PRODUCTS_ID) REFERENCES PRODUCTS(PRODUCTS_ID)
);

CREATE TABLE IF NOT EXISTS ORDER_ITEMS(
   PRODUCTS_ID INT,
   ORDERS_ID INT,
   ORDER_ITEMS_QUANTITY VARCHAR(50),
   ORDER_ITEMS_PRICE VARCHAR(50),
   PRIMARY KEY(PRODUCTS_ID, ORDERS_ID),
   FOREIGN KEY(PRODUCTS_ID) REFERENCES PRODUCTS(PRODUCTS_ID),
   FOREIGN KEY(ORDERS_ID) REFERENCES ORDERS(ORDERS_ID)
);


