CREATE TABLE IF NOT EXISTS CATEGORIES(
   CATEGORIES_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   CATEGORIES_DESCRIPTION VARCHAR(255),
   CATEGORIES_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTS(
   PRODUCTS_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   PRODUCTS_NAME VARCHAR(50) NOT NULL,
   PRODUCTS_PRICE DECIMAL(15,2) NOT NULL,
   PRODUCTS_STOCK INT NOT NULL,
   PRODUCTS_CATEGORIES_ID INt NOT NULL,
   FOREIGN KEY(PRODUCTS_CATEGORIES_ID) REFERENCES CATEGORIES(CATEGORIES_ID) ON DELETE CASCADE
);



CREATE TABLE IF NOT EXISTS CUSTOMERS(
   CUSTOMERS_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   CUSTOMERS_FIRSTNAME VARCHAR(255) NOT NULL,
   CUSTOMERS_LASTNAME VARCHAR(255) NOT NULL,
   CUSTOMERS_EMAIL VARCHAR(255) NOT NULL,
   CUSTOMERS_CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TYPE ORDER_STATUS AS ENUM ('PAID','SHIPPED','CANCELLED','PENDING'); 


CREATE TABLE IF NOT EXISTS ORDERS(
   ORDERS_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   ORDERS_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   ORDERS_STATUS ORDER_STATUS NOT NULL,
   ORDERS_CUSTOMERS_ID INT NOT NULL,
   FOREIGN KEY(ORDERS_CUSTOMERS_ID) REFERENCES CUSTOMERS(CUSTOMERS_ID) ON DELETE CASCADE
);



CREATE TABLE IF NOT EXISTS ORDER_ITEMS(
   ORDER_ITEMS_PRODUCTS_ID INT,
   ORDER_ITEMS_ORDERS_ID INT,
   ORDER_ITEMS_QUANTITY INT,
   ORDER_ITEMS_PRICE DECIMAL(15,2),
   PRIMARY KEY(ORDER_ITEMS_PRODUCTS_ID, ORDER_ITEMS_ORDERS_ID),
   FOREIGN KEY(ORDER_ITEMS_PRODUCTS_ID) REFERENCES PRODUCTS(PRODUCTS_ID) ON DELETE CASCADE,
   FOREIGN KEY(ORDER_ITEMS_ORDERS_ID) REFERENCES ORDERS(ORDERS_ID) ON DELETE CASCADE
);



